---
- name: "1.1.1.1 - 1.1.1.7"
  copy:
    dest: /etc/modprobe.d/disabled-fs-ansible.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      install cramfs /bin/true
      install freevxfs /bin/true
      install jffs2 /bin/true
      install hfs /bin/true
      install hfsplus /bin/true
      install squashfs /bin/true
      install udf /bin/true
