---
- name: "3.1.2"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: no
  with_items:
    - {name: "net.ipv4.conf.all.send_redirects", value: 0}
    - {name: "net.ipv4.conf.default.send_redirects", value: 0}
