---
- name: "1.5.1"
  copy:
    dest: /etc/security/limits.d/10-core-dump-restricted.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      *               hard    core            0

- name: "1.5.1"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: no
  with_items:
    - {name: "fs.suid_dumpable", value: 0}
