---
- hosts: all
  name: CLOUD INIT
  tasks:
    - name: COPY CONFIG FILES
      copy:
        src: ".{{ item.dest }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { dest: '/etc/cloud/cloud.cfg.d/03_apt.cfg', mode: "0600" }
