---
- hosts: all
  name: CLOUD INIT
  tasks:
    - name: REMOVE FLAKE CLOUD CONFIG
      file:
        state: absent
        path: /etc/cloud/cloud.cfg.d/99-fake_cloud.cfg

    - name: COPY CONFIG FILES
      copy:
        src: ".{{ item.dest }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { dest: '/etc/cloud/cloud.cfg.d/01_netplan.cfg', mode: "0600" }
        - { dest: '/etc/cloud/cloud.cfg.d/02_hosts.cfg', mode: "0600" }
