---
- hosts: all
  tasks:
    - name: REMOVE PI USER
      user:
        name: pi
        remove: yes
        state: absent

    - name: REMOVE NET-MODS AND DHCPCD5
      apt:
        name:
          - raspberrypi-net-mods
          - dhcpcd5
        purge: yes
        state: absent

    - name: DISABLE SSH HOST KEYS SERVICE
      systemd:
        name: regenerate_ssh_host_keys
        enabled: no

    - name: ENABLE SYSTEMD NETWORKD
      systemd:
        name: systemd-networkd
        enabled: yes

    - name: ENABLE SYSTEMD RESOLVED
      systemd:
        name: systemd-resolved
        enabled: yes

    - name: INSTALL CLOUD-INIT
      apt:
        name:
          - netplan.io
          - cloud-init
        state: present

    - name: CREATE /RUN/SYSTEMD
      file:
        path: /run/systemd
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: CREATE /RUN/SYSTEMD/RESOLVE
      file:
        path: /run/systemd/resolve
        owner: systemd-resolve
        group: systemd-resolve
        mode: "0755"
        state: directory

    - name: COPY RESOLV TO SYSTEMD RESOLVE
      copy:
        remote_src: yes
        src: /etc/resolv.conf
        dest: /run/systemd/resolve/resolv.conf
        owner: systemd-resolve
        group: systemd-resolve
        mode: "0644"

    - name: SYMLINK RESOLV TO SYSTEMD RESOLVE
      file:
        path: /etc/resolv.conf
        src: /run/systemd/resolve/resolv.conf
        owner: root
        group: root
        mode: "0644"
        force: yes
        state: link

    - name: COPY CONFIG FILES
      copy:
        src: ".{{ item.dest }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { dest: '/etc/cloud/cloud.cfg.d/01_netplan.cfg', mode: "0600" }
