---
- hosts: all
  name: BASE
  tasks:
    - name: REPLACE /BOOT/FIRMWARE/CMDLINE.TXT
      copy:
        src: ./boot/firmware/cmdline.txt
        dest: /boot/firmware/cmdline.txt

    - name: SET /BOOT/firmware/CONFIG.TXT FLAGS
      lineinfile:
        path: /boot/firmware/config.txt 
        line: "{{ item }}"
      with_items:
        - "hdmi_force_hotplug=1"
        - "dtoverlay=disable-bt"
        - "dtoverlay=disable-wifi"

    - name: CREATE /RUN/SYSTEMD
      file:
        path: /run/systemd
        owner: root
        group: root
        mode: "0755"
        state: directory

    - name: CREATE /RUN/SYSTEMD/RESOLVE
      file:
        path: /run/systemd/resolve
        owner: systemd-resolve
        group: systemd-resolve
        mode: "0755"
        state: directory

    - name: SET SYSTEMD RESOLVE FOR IMAGE BUILDS
      copy:
        dest: /run/systemd/resolve/stub-resolv.conf
        content: "nameserver 1.1.1.1" # chroots don't have ns
        owner: systemd-resolve
        group: systemd-resolve
        mode: "0644"

    - name: DISABLE UBUNTU MOTD-NEWS
      lineinfile:
        dest: /etc/default/motd-news
        state: present
        regexp: '^ENABLED='
        line: 'ENABLED=0'

    - name: UPDATE SOURCES
      copy: 
        src: ./etc/apt/sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: "0644"

    - name: REMOVE SNAPD
      apt:
        name:
          - snapd
        state: absent
        purge: yes
        autoremove: yes

    - name: UPDATE ALL PACKAGES
      apt:
        update_cache: yes
        upgrade: yes

    - name: MODIFY EFI CHECK FROM FLASH KERNEL SO WE CAN FLASH IN ARM CHROOT
      lineinfile:
        path: /usr/share/flash-kernel/functions
        regexp: '^if \[ -d /sys/firmware/efi \]; then'
        line: 'if false; then'

    - name: FLASH KERNEL
      shell: "flash-kernel"
      environment:
        FK_MACHINE: "Raspberry Pi 4 Model B"

    - name: INSTALL UTILITIES
      apt:
        name:
          - net-tools
          - vim
          - unzip
          - tar
          - jq
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
        state: present

    - name: ADD TAILSCALE APT REPOSITORY KEY
      apt_key:
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
        state: present
    
    - name: ADD TAILSCALE APT REPOSITORY
      apt_repository:
        repo: "deb [arch=arm64] https://pkgs.tailscale.com/stable/ubuntu jammy main"
        state: present

    - name: INSTALL TAILSCALE
      apt:
        name:
          - tailscale
    