
variable "image_mount_path" {
  type    = string
  default = "/mnt/packer-chroot/harden"
}

source "arm" "autogenerated_1" {
  file_checksum_type    = "none"
  file_target_extension = "tar.gz"
  file_unarchive_cmd    = ["tar", "-xpf", "$ARCHIVE_PATH", "-C", "$MOUNTPOINT"]
  file_urls             = ["file:///images/cloud-init.tar.gz"]
  image_build_method    = "new"
  image_chroot_env      = ["PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"]
  image_mount_path      = "${var.image_mount_path}"
  image_partitions {
    filesystem   = "ext4"
    mountpoint   = "/"
    name         = "root"
    size         = "3.4G"
    start_sector = "526336"
    type         = "83"
  }
  image_path                   = "harden.tar.gz"
  image_size                   = "3.8G"
  image_type                   = "dos"
  qemu_binary_destination_path = "/usr/bin/qemu-arm-static"
  qemu_binary_source_path      = "/usr/bin/qemu-arm-static"
}

build {
  sources = ["source.arm.autogenerated_1"]

  provisioner "ansible" {
    ansible_env_vars = ["ANSIBLE_RETRY_FILES_ENABLED=0"]
    extra_arguments  = ["-v", "--connection=chroot"]
    inventory_file   = "./harden/ansible/hosts"
    playbook_file    = "./harden/ansible/site.yml"
  }

}
