---
- name: "3.3.1"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: no
  with_items:
    - {name: "net.ipv6.conf.all.accept_ra", value: 0}
    - {name: "net.ipv6.conf.default.accept_ra", value: 0}

- name: "3.3.2"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: no
  with_items:
    - {name: "net.ipv6.conf.all.accept_redirects", value: 0}
    - {name: "net.ipv6.conf.default.accept_redirects", value: 0}

- name: "3.3.3"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: no
  with_items:
    - {name: "net.ipv6.conf.all.disable_ipv6", value: 1}
    - {name: "net.ipv6.conf.default.disable_ipv6", value: 1}
